### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by dillfrescott** [stv0g/gose#41] opened 2022-10-30 03:05 UTC
Is there a way to enable a page that displays the name of the file and a download button instead of directly hotlinking the file? This would be a nice feature!

**Comment by stv0g** [comment] 2022-10-31 10:33
Yes this would definitely be quite nice.
I am currently a bit busy. But contributions are very welcome :)

This is also a duplicate of #16. Hence i will close this issue.

**Closed by stv0g** 2022-10-31 10:33 UTC
